name: Assignment 1 CI

on:
  push:
    branches:
      - 'assignment1'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make python3 libgtest-dev python3-pip
          python3 -m pip install pytest

      - name: Build
        working-directory: Assignment1
        run: make

      - name: Run C++ tests
        working-directory: Assignment1
        run: |
          make test
          ./test

      - name: Run Python tests
        working-directory: Assignment1
        run: |
          python3 -m pytest tests.py -v
