name: Assignment 2 CI

on:
  push:
    paths:
      - 'Assignment2/**'
  pull_request:
    paths:
      - 'Assignment2/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make libgtest-dev
