name: Assignment 3 CI

on:
  push:
    branches:
      - 'assignment3'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make 
          
      - name: Build
        working-directory: Assignment3
        run: make
        
      - name: Run C++ tests
        working-directory: Assignment3
        run: |
          make test
          ./test
