name: CI Workflow

on: [push, pull_request]

jobs:
  test-assignments:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        assignment: [1]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make python3 libgtest-dev

      - name: Build Assignment${{ matrix.assignment }}
        working-directory: Assignment${{ matrix.assignment }}
        run: make
        
      - name: Build and run Assignment${{ matrix.assignment }} tests 
        working-directory: Assignment${{ matrix.assignment }}
        run: |
          make test
          ./test
